name: Renovar token de Instagram

on:
  schedule:
    - cron: "0 15 1 * *"
  workflow_dispatch: {}

jobs:
  renovar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Renovar
        env:
          IG_TOKEN: ${{ secrets.IG_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python refrescar_token.py
